import type {
  HostelBuilding, HostelRoom, HostelStudent, RoomAllocationRecord,
  WardenRecord, HostelAttendanceRecord, MessMenuRecord, VisitorRecord,
  GatePassRecord, ComplaintRecord, HostelInventoryItem, HostelFeeRecord,
  MedicalEmergencyRecord, DisciplinaryIncidentRecord, AiHostelInsight
} from './types';

export const mockHostelBuildings: HostelBuilding[] = [
  {
    id: 'BLD-01',
    buildingName: 'Tagore Senior Boys Block A',
    buildingCode: 'BLK-A',
    genderCategory: 'Boys Hostel',
    totalFloors: 4,
    totalRooms: 60,
    totalCapacityBeds: 180,
    occupiedBeds: 168,
    availableBeds: 12,
    chiefWardenName: 'Dr. Ramesh Chandra',
    chiefWardenPhone: '+91 98765 11223',
    status: 'Operational',
  },
  {
    id: 'BLD-02',
    buildingName: 'Sarojini Girls Residence Block B',
    buildingCode: 'BLK-B',
    genderCategory: 'Girls Hostel',
    totalFloors: 4,
    totalRooms: 50,
    totalCapacityBeds: 150,
    occupiedBeds: 142,
    availableBeds: 8,
    chiefWardenName: 'Mrs. Sunita Deshmukh',
    chiefWardenPhone: '+91 98765 33445',
    status: 'Operational',
  },
  {
    id: 'BLD-03',
    buildingName: 'Ramanujan Junior Boys Block C',
    buildingCode: 'BLK-C',
    genderCategory: 'Boys Hostel',
    totalFloors: 3,
    totalRooms: 40,
    totalCapacityBeds: 120,
    occupiedBeds: 110,
    availableBeds: 10,
    chiefWardenName: 'Prof. Alok Verma',
    chiefWardenPhone: '+91 98765 55667',
    status: 'Operational',
  },
];

export const mockHostelRooms: HostelRoom[] = [
  {
    id: 'RM-101',
    roomNumber: 'A-101',
    buildingName: 'Tagore Senior Boys Block A',
    floorNo: 1,
    roomType: 'Triple Sharing',
    capacityBeds: 3,
    occupiedBeds: 3,
    availableBeds: 0,
    monthlyFee: 12000,
    furnitureDetails: ['3 Cot Beds', '3 Study Tables', '3 Wardrobes', '1 Ceiling Fan'],
    condition: 'Excellent',
    status: 'Fully Occupied',
  },
  {
    id: 'RM-102',
    roomNumber: 'A-102',
    buildingName: 'Tagore Senior Boys Block A',
    floorNo: 1,
    roomType: 'Double Sharing',
    capacityBeds: 2,
    occupiedBeds: 1,
    availableBeds: 1,
    monthlyFee: 15000,
    furnitureDetails: ['2 Cot Beds', '2 Study Desks', '2 Wardrobes', 'Attached Bath'],
    condition: 'Good',
    status: 'Available',
  },
  {
    id: 'RM-201',
    roomNumber: 'B-201',
    buildingName: 'Sarojini Girls Residence Block B',
    floorNo: 2,
    roomType: 'Double Sharing',
    capacityBeds: 2,
    occupiedBeds: 2,
    availableBeds: 0,
    monthlyFee: 15000,
    furnitureDetails: ['2 Cot Beds', '2 Study Desks', '2 Wardrobes', 'Attached Bath'],
    condition: 'Excellent',
    status: 'Fully Occupied',
  },
  {
    id: 'RM-202',
    roomNumber: 'B-202',
    buildingName: 'Sarojini Girls Residence Block B',
    floorNo: 2,
    roomType: 'Single Deluxe',
    capacityBeds: 1,
    occupiedBeds: 0,
    availableBeds: 1,
    monthlyFee: 22000,
    furnitureDetails: ['1 Single Bed', '1 Executive Desk', '1 Large Wardrobe', 'AC'],
    condition: 'Excellent',
    status: 'Available',
  },
];

export const mockHostelStudents: HostelStudent[] = [
  {
    id: 'HST-101',
    studentId: 'STU-104',
    studentName: 'Aarav Sharma',
    classGrade: 'Class 10-A',
    gender: 'Male',
    buildingName: 'Tagore Senior Boys Block A',
    roomNumber: 'A-101',
    bedNumber: 'Bed #1',
    guardianName: 'Mahesh Sharma',
    guardianPhone: '+91 98110 44332',
    emergencyContact: '+91 98110 44332',
    medicalConditions: 'Mild Asthma (Inhaler in Room)',
    feeStatus: 'Paid',
    status: 'Resident',
  },
  {
    id: 'HST-102',
    studentId: 'STU-108',
    studentName: 'Siya Patel',
    classGrade: 'Class 11-B',
    gender: 'Female',
    buildingName: 'Sarojini Girls Residence Block B',
    roomNumber: 'B-201',
    bedNumber: 'Bed #1',
    guardianName: 'Pravin Patel',
    guardianPhone: '+91 98330 11223',
    emergencyContact: '+91 98330 11223',
    feeStatus: 'Paid',
    status: 'Resident',
  },
  {
    id: 'HST-103',
    studentId: 'STU-112',
    studentName: 'Vivaan Mehta',
    classGrade: 'Class 9-C',
    gender: 'Male',
    buildingName: 'Tagore Senior Boys Block A',
    roomNumber: 'A-101',
    bedNumber: 'Bed #2',
    guardianName: 'Sanjay Mehta',
    guardianPhone: '+91 98440 99887',
    emergencyContact: '+91 98440 99887',
    feeStatus: 'Pending',
    status: 'Resident',
  },
  {
    id: 'HST-104',
    studentId: 'STU-115',
    studentName: 'Ananya Sen',
    classGrade: 'Class 12-A',
    gender: 'Female',
    buildingName: 'Sarojini Girls Residence Block B',
    roomNumber: 'B-201',
    bedNumber: 'Bed #2',
    guardianName: 'Dipankar Sen',
    guardianPhone: '+91 98220 33445',
    emergencyContact: '+91 98220 33445',
    feeStatus: 'Paid',
    status: 'Resident',
  },
];

export const mockRoomAllocations: RoomAllocationRecord[] = [
  {
    id: 'ALC-901',
    studentId: 'STU-104',
    studentName: 'Aarav Sharma',
    classGrade: 'Class 10-A',
    buildingName: 'Tagore Senior Boys Block A',
    roomNumber: 'A-101',
    bedNumber: 'Bed #1',
    allocationDate: '2025-06-01',
    validTillDate: '2026-05-31',
    allocatedBy: 'Chief Warden Ramesh Chandra',
    status: 'Active',
  },
  {
    id: 'ALC-902',
    studentId: 'STU-108',
    studentName: 'Siya Patel',
    classGrade: 'Class 11-B',
    buildingName: 'Sarojini Girls Residence Block B',
    roomNumber: 'B-201',
    bedNumber: 'Bed #1',
    allocationDate: '2025-06-01',
    validTillDate: '2026-05-31',
    allocatedBy: 'Warden Sunita Deshmukh',
    status: 'Active',
  },
];

export const mockWardens: WardenRecord[] = [
  {
    id: 'WRD-101',
    name: 'Dr. Ramesh Chandra',
    role: 'Chief Warden',
    assignedBuilding: 'Tagore Senior Boys Block A',
    phone: '+91 98765 11223',
    email: 'ramesh.c@school.edu',
    dutyShift: 'Morning (6 AM - 2 PM)',
    attendanceStatus: 'Present',
  },
  {
    id: 'WRD-102',
    name: 'Mrs. Sunita Deshmukh',
    role: 'Chief Warden',
    assignedBuilding: 'Sarojini Girls Residence Block B',
    phone: '+91 98765 33445',
    email: 'sunita.d@school.edu',
    dutyShift: 'Morning (6 AM - 2 PM)',
    attendanceStatus: 'Present',
  },
  {
    id: 'WRD-103',
    name: 'Rajiv Malhotra',
    role: 'Night Supervisor',
    assignedBuilding: 'Tagore Senior Boys Block A',
    phone: '+91 98765 77889',
    email: 'rajiv.m@school.edu',
    dutyShift: 'Night (10 PM - 6 AM)',
    attendanceStatus: 'On Duty',
  },
];

export const mockHostelAttendance: HostelAttendanceRecord[] = [
  {
    id: 'ATT-01',
    studentId: 'STU-104',
    studentName: 'Aarav Sharma',
    roomNumber: 'A-101',
    buildingName: 'Tagore Senior Boys Block A',
    date: '2026-07-22',
    morningStatus: 'Present',
    nightRollCallStatus: 'Present',
  },
  {
    id: 'ATT-02',
    studentId: 'STU-112',
    studentName: 'Vivaan Mehta',
    roomNumber: 'A-101',
    buildingName: 'Tagore Senior Boys Block A',
    date: '2026-07-22',
    morningStatus: 'Present',
    nightRollCallStatus: 'Late Return',
    returnTime: '09:48 PM',
    remarks: 'Late entry by 18 mins after 09:30 PM curfew.',
  },
];

export const mockMessMenu: MessMenuRecord[] = [
  {
    id: 'MENU-1',
    dayOfWeek: 'Monday',
    breakfast: 'Idli Sambar & Chutney, Masala Tea / Milk, Boiled Eggs',
    lunch: 'Roti, Paneer Butter Masala, Dal Tadka, Jeera Rice, Curd & Salad',
    snacks: 'Samosa & Mint Chutney, Coffee / Milk',
    dinner: 'Chapati, Mix Veg Curry, Rajma Dal, Steamed Rice, Gulab Jamun',
    dietType: 'Pure Veg',
    qualityRating: 4.8,
  },
  {
    id: 'MENU-2',
    dayOfWeek: 'Tuesday',
    breakfast: 'Aloo Paratha with Butter, Curd, Coffee / Tea',
    lunch: 'Roti, Chana Masala, Veg Biryani, Boondi Raita, Salad',
    snacks: 'Veg Cutlet, Tea / Milk',
    dinner: 'Chapati, Butter Chicken / Paneer Kadhai, Yellow Dal, Steamed Rice',
    dietType: 'Non-Veg Available',
    qualityRating: 4.7,
  },
];

export const mockVisitors: VisitorRecord[] = [
  {
    id: 'VIS-401',
    visitorName: 'Mahesh Sharma',
    relation: 'Father',
    studentName: 'Aarav Sharma',
    studentRoom: 'A-101',
    phone: '+91 98110 44332',
    visitDate: '2026-07-22',
    entryTime: '04:30 PM',
    exitTime: '06:00 PM',
    gatePassId: 'GP-801',
    status: 'Exited',
  },
  {
    id: 'VIS-402',
    visitorName: 'Pravin Patel',
    relation: 'Father',
    studentName: 'Siya Patel',
    studentRoom: 'B-201',
    phone: '+91 98330 11223',
    visitDate: '2026-07-23',
    entryTime: '10:15 AM',
    gatePassId: 'GP-802',
    status: 'In Campus',
  },
];

export const mockGatePasses: GatePassRecord[] = [
  {
    id: 'GP-801',
    studentId: 'STU-104',
    studentName: 'Aarav Sharma',
    roomNumber: 'A-101',
    buildingName: 'Tagore Senior Boys Block A',
    passType: 'Local Outing',
    outTime: '04:00 PM',
    expectedInTime: '07:30 PM',
    actualInTime: '07:15 PM',
    approvedBy: 'Chief Warden Ramesh Chandra',
    status: 'Returned',
  },
  {
    id: 'GP-802',
    studentId: 'STU-108',
    studentName: 'Siya Patel',
    roomNumber: 'B-201',
    buildingName: 'Sarojini Girls Residence Block B',
    passType: 'Weekend Leave',
    outTime: '09:00 AM',
    expectedInTime: '06:00 PM (Tomorrow)',
    approvedBy: 'Warden Sunita Deshmukh',
    status: 'Out Side',
  },
];

export const mockComplaints: ComplaintRecord[] = [
  {
    id: 'CMP-301',
    studentName: 'Aarav Sharma',
    roomNumber: 'A-101',
    buildingName: 'Tagore Senior Boys Block A',
    category: 'Electrical',
    description: 'Ceiling fan making squeaking noise in A-101.',
    dateFiled: '2026-07-21',
    priority: 'Medium',
    assignedTech: 'Electrician Mohan Kumar',
    status: 'In Progress',
  },
  {
    id: 'CMP-302',
    studentName: 'Siya Patel',
    roomNumber: 'B-201',
    buildingName: 'Sarojini Girls Residence Block B',
    category: 'Plumbing',
    description: 'Bathroom tap leak in B-201.',
    dateFiled: '2026-07-20',
    priority: 'High',
    assignedTech: 'Plumber Ramesh',
    status: 'Resolved',
  },
];

export const mockHostelInventory: HostelInventoryItem[] = [
  {
    id: 'INV-101',
    itemName: 'Single Cot Wooden Beds',
    category: 'Furniture',
    totalQuantity: 450,
    inUseQuantity: 420,
    inStockQuantity: 25,
    damagedQuantity: 5,
    location: 'Central Furniture Store & Rooms',
    lastAuditDate: '2026-07-01',
  },
  {
    id: 'INV-102',
    itemName: 'Orthopedic Foam Mattresses',
    category: 'Bedding & Linen',
    totalQuantity: 450,
    inUseQuantity: 420,
    inStockQuantity: 22,
    damagedQuantity: 8,
    location: 'Hostel Block Stores',
    lastAuditDate: '2026-07-01',
  },
];

export const mockHostelFees: HostelFeeRecord[] = [
  {
    id: 'FEE-501',
    studentId: 'STU-104',
    studentName: 'Aarav Sharma',
    roomNumber: 'A-101',
    buildingName: 'Tagore Senior Boys Block A',
    termSemester: 'Term 1 (2025-26)',
    hostelFeeAmount: 45000,
    messFeeAmount: 25000,
    totalFee: 70000,
    amountPaid: 70000,
    dueDate: '2025-07-15',
    status: 'Paid',
  },
  {
    id: 'FEE-502',
    studentId: 'STU-112',
    studentName: 'Vivaan Mehta',
    roomNumber: 'A-101',
    buildingName: 'Tagore Senior Boys Block A',
    termSemester: 'Term 1 (2025-26)',
    hostelFeeAmount: 45000,
    messFeeAmount: 25000,
    totalFee: 70000,
    amountPaid: 35000,
    dueDate: '2025-07-15',
    status: 'Partial',
  },
];

export const mockMedicalCases: MedicalEmergencyRecord[] = [
  {
    id: 'MED-701',
    studentId: 'STU-104',
    studentName: 'Aarav Sharma',
    roomNumber: 'A-101',
    buildingName: 'Tagore Senior Boys Block A',
    symptomsDetails: 'Mild wheezing & shortness of breath due to weather shift.',
    reportedDate: '2026-07-18',
    severity: 'Mild',
    infirmaryAttendant: 'Nurse Mary Kutty',
    actionTaken: 'Nebulizer administered in infirmary; parent notified.',
    hospitalized: false,
    parentNotified: true,
    status: 'Recovered',
  },
];

export const mockDisciplinaryIncidents: DisciplinaryIncidentRecord[] = [
  {
    id: 'DISC-901',
    studentId: 'STU-112',
    studentName: 'Vivaan Mehta',
    roomNumber: 'A-101',
    buildingName: 'Tagore Senior Boys Block A',
    violationType: 'Curfew Breach',
    date: '2026-07-22',
    reportedBy: 'Night Supervisor Rajiv Malhotra',
    actionTaken: 'Verbal Warning',
    status: 'Resolved',
  },
];

export const mockAiHostelInsights: AiHostelInsight[] = [
  {
    id: 'INS-HST-01',
    type: 'occupancy',
    title: 'Optimal Bed Allocation Optimization',
    description: 'Sarojini Girls Block B is at 94.6% capacity. Reallocating 5 upcoming admissions to Block B Deluxe Wing maximizes revenue.',
    metric: '94.6% Occupancy',
    actionText: 'View Allocation Matrix',
    impact: 'High',
  },
  {
    id: 'INS-HST-02',
    type: 'maintenance',
    title: 'Preventive Plumbing Inspection Alert',
    description: '3 water leakage complaints logged in Block A Floor 2. A central pipe pressure check is recommended.',
    metric: '3 Complaints',
    actionText: 'Schedule Work Order',
    impact: 'Medium',
  },
  {
    id: 'INS-HST-03',
    type: 'mess_waste',
    title: 'Mess Consumption & Food Waste Reduction',
    description: 'Dinner consumption data shows 14% surplus rice preparation on Tuesdays. Adjusting prep quantity saves ₹12,500/month.',
    metric: '14% Waste Reduction',
    actionText: 'Update Kitchen Recipe Scale',
    impact: 'High',
  },
];
