import { UserRole } from '@edutrack/shared-types';
import { PERMISSIONS } from './PERMISSIONS';
import type { Permission } from './PERMISSIONS';

// Helper for wildcard permissions
const ALL_PERMISSIONS = Object.values(PERMISSIONS) as Permission[];

export const ROLE_PERMISSIONS: Partial<Record<UserRole, Permission[]>> = {
  [UserRole.ORGANIZATION_ADMIN]: [
    PERMISSIONS.ORGANIZATION_VIEW,
    PERMISSIONS.ORGANIZATION_EDIT,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.COMMUNICATION_CREATE,
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.SECURITY_VIEW,
  ],

  [UserRole.PRINCIPAL]: [
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.COMMUNICATION_CREATE,
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.EVENTS_CREATE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.LIBRARY_VIEW,
    PERMISSIONS.TRANSPORT_VIEW,
  ],

  [UserRole.ACADEMIC_COORDINATOR]: [
    PERMISSIONS.ACADEMIC_VIEW,
    PERMISSIONS.ACADEMIC_CREATE,
    PERMISSIONS.ACADEMIC_EDIT,
    PERMISSIONS.TEACHERS_VIEW,
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.EXAMS_VIEW,
    PERMISSIONS.EXAMS_SCHEDULE,
    PERMISSIONS.EXAMS_PUBLISH,
    PERMISSIONS.EXAMS_MONITOR,
    PERMISSIONS.LESSON_PLAN_VIEW,
    PERMISSIONS.LESSON_PLAN_APPROVE,
    PERMISSIONS.LESSON_PLAN_REJECT,
    PERMISSIONS.ONLINE_CLASS_SCHEDULE,
    PERMISSIONS.ONLINE_CLASS_MONITOR,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.EVENTS_CREATE,
  ],


  [UserRole.ACCOUNTANT]: [
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.FEES_CREATE,
    PERMISSIONS.FEES_EDIT,
    PERMISSIONS.FEES_DELETE,
    PERMISSIONS.PAYROLL_VIEW,
    PERMISSIONS.PAYROLL_CREATE,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],

  [UserRole.HR]: [
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.HR_CREATE,
    PERMISSIONS.HR_EDIT,
    PERMISSIONS.HR_DELETE,
    PERMISSIONS.PAYROLL_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],

  [UserRole.LIBRARIAN]: [
    PERMISSIONS.LIBRARY_VIEW,
    PERMISSIONS.LIBRARY_CREATE,
    PERMISSIONS.LIBRARY_EDIT,
    PERMISSIONS.LIBRARY_DELETE,
    PERMISSIONS.REPORTS_VIEW,
  ],

  [UserRole.TRANSPORT_MANAGER]: [
    PERMISSIONS.TRANSPORT_VIEW,
    PERMISSIONS.TRANSPORT_CREATE,
    PERMISSIONS.TRANSPORT_EDIT,
    PERMISSIONS.TRANSPORT_DELETE,
    PERMISSIONS.REPORTS_VIEW,
  ],

  [UserRole.HOSTEL_MANAGER]: [
    PERMISSIONS.HOSTEL_VIEW,
    PERMISSIONS.HOSTEL_CREATE,
    PERMISSIONS.HOSTEL_EDIT,
    PERMISSIONS.VISITOR_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],

  [UserRole.RECEPTIONIST]: [
    PERMISSIONS.ADMISSIONS_VIEW,
    PERMISSIONS.ADMISSIONS_CREATE,
    PERMISSIONS.VISITOR_VIEW,
    PERMISSIONS.VISITOR_CREATE,
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],

  [UserRole.SECURITY]: [
    PERMISSIONS.SECURITY_VIEW,
    PERMISSIONS.SECURITY_CREATE,
    PERMISSIONS.VISITOR_VIEW,
    PERMISSIONS.VISITOR_CREATE,
  ],
};
