import type {
  BusVehicle, StudentTransportAssignment, BusRoute, DriverRecord, TripRecord,
  GpsTrackingPoint, FuelLogEntry, MaintenanceRecord, VehicleDocument,
  TransportRequestItem, SafetyIncidentRecord, AiTransportInsight
} from './types';

export const mockBuses: BusVehicle[] = [
  {
    id: 'BUS-01',
    busNumber: 'BUS-01',
    registrationNumber: 'KA-01-EQ-1042',
    capacity: 45,
    assignedDriverId: 'DRV-101',
    assignedDriverName: 'Rajesh Kumar',
    assignedRouteId: 'RT-01',
    assignedRouteName: 'North Circuit Express',
    status: 'Active',
    fuelType: 'Diesel',
    currentFuelLevelPercent: 82,
    insuranceExpiry: '2026-11-15',
    fitnessExpiry: '2027-02-10',
    pollutionExpiry: '2026-09-30',
    permitExpiry: '2027-05-20',
    totalKmDriven: 42500,
    lastServiceDate: '2026-06-12',
  },
  {
    id: 'BUS-02',
    busNumber: 'BUS-02',
    registrationNumber: 'KA-01-EQ-1045',
    capacity: 45,
    assignedDriverId: 'DRV-102',
    assignedDriverName: 'Suresh Patil',
    assignedRouteId: 'RT-02',
    assignedRouteName: 'South City Commute',
    status: 'Active',
    fuelType: 'Diesel',
    currentFuelLevelPercent: 65,
    insuranceExpiry: '2026-10-01',
    fitnessExpiry: '2026-12-18',
    pollutionExpiry: '2026-08-25',
    permitExpiry: '2027-01-15',
    totalKmDriven: 38900,
    lastServiceDate: '2026-05-28',
  },
  {
    id: 'BUS-03',
    busNumber: 'BUS-03',
    registrationNumber: 'KA-01-EV-2090',
    capacity: 36,
    assignedDriverId: 'DRV-103',
    assignedDriverName: 'Vikram Singh',
    assignedRouteId: 'RT-03',
    assignedRouteName: 'East Campus Line',
    status: 'Active',
    fuelType: 'EV',
    currentFuelLevelPercent: 94,
    insuranceExpiry: '2027-03-10',
    fitnessExpiry: '2027-08-01',
    pollutionExpiry: '2027-08-01',
    permitExpiry: '2027-09-12',
    totalKmDriven: 18200,
    lastServiceDate: '2026-07-01',
  },
  {
    id: 'BUS-04',
    busNumber: 'BUS-04',
    registrationNumber: 'KA-01-EQ-1102',
    capacity: 52,
    assignedDriverId: 'DRV-104',
    assignedDriverName: 'Ramesh Gowda',
    assignedRouteId: 'RT-04',
    assignedRouteName: 'West Suburban Route',
    status: 'In Servicing',
    fuelType: 'Diesel',
    currentFuelLevelPercent: 40,
    insuranceExpiry: '2026-08-14',
    fitnessExpiry: '2026-09-10',
    pollutionExpiry: '2026-08-01',
    permitExpiry: '2026-11-30',
    totalKmDriven: 51200,
    lastServiceDate: '2026-07-20',
  },
  {
    id: 'BUS-05',
    busNumber: 'BUS-05',
    registrationNumber: 'KA-01-CNG-3011',
    capacity: 40,
    assignedDriverId: 'DRV-105',
    assignedDriverName: 'Anand Verma',
    assignedRouteId: 'RT-05',
    assignedRouteName: 'Central Metro Feeder',
    status: 'Active',
    fuelType: 'CNG',
    currentFuelLevelPercent: 70,
    insuranceExpiry: '2027-01-20',
    fitnessExpiry: '2027-04-14',
    pollutionExpiry: '2026-11-10',
    permitExpiry: '2027-06-05',
    totalKmDriven: 29400,
    lastServiceDate: '2026-06-25',
  },
];

export const mockStudentsTransport: StudentTransportAssignment[] = [
  {
    id: 'STU-TR-101',
    studentId: 'STU-104',
    studentName: 'Aarav Sharma',
    classGrade: 'Class 10-A',
    busNumber: 'BUS-01',
    routeName: 'North Circuit Express',
    pickupPoint: 'Stop #3 - Hebbal Circle',
    dropPoint: 'School Main Gate',
    pickupTime: '07:15 AM',
    dropTime: '03:45 PM',
    parentPhone: '+91 98110 44332',
    status: 'Assigned',
  },
  {
    id: 'STU-TR-102',
    studentId: 'STU-108',
    studentName: 'Siya Patel',
    classGrade: 'Class 11-B',
    busNumber: 'BUS-01',
    routeName: 'North Circuit Express',
    pickupPoint: 'Stop #5 - Manyata Tech Park',
    dropPoint: 'School Main Gate',
    pickupTime: '07:25 AM',
    dropTime: '03:35 PM',
    parentPhone: '+91 98330 11223',
    status: 'Assigned',
  },
  {
    id: 'STU-TR-103',
    studentId: 'STU-112',
    studentName: 'Vivaan Mehta',
    classGrade: 'Class 9-C',
    busNumber: 'BUS-02',
    routeName: 'South City Commute',
    pickupPoint: 'Stop #2 - Jayanagar 4th Block',
    dropPoint: 'School Secondary Gate',
    pickupTime: '07:10 AM',
    dropTime: '03:50 PM',
    parentPhone: '+91 98440 99887',
    status: 'Assigned',
  },
  {
    id: 'STU-TR-104',
    studentId: 'STU-115',
    studentName: 'Rohan Gupta',
    classGrade: 'Class 8-A',
    busNumber: 'BUS-03',
    routeName: 'East Campus Line',
    pickupPoint: 'Stop #4 - Whitefield Forum',
    dropPoint: 'School Main Gate',
    pickupTime: '07:05 AM',
    dropTime: '04:00 PM',
    parentPhone: '+91 98220 33445',
    status: 'Assigned',
  },
];

export const mockBusRoutes: BusRoute[] = [
  {
    id: 'RT-01',
    routeName: 'North Circuit Express',
    routeCode: 'NCR-01',
    busNumber: 'BUS-01',
    driverName: 'Rajesh Kumar',
    attendantName: 'Sunita Devi',
    totalStops: 6,
    totalDistanceKm: 18.5,
    estimatedDurationMins: 45,
    totalStudentsAssigned: 38,
    status: 'Operational',
    stops: [
      { id: 'SP-101', stopName: 'Yelahanka Satellite Town', sequenceNo: 1, morningPickupTime: '07:00 AM', eveningDropTime: '04:10 PM', studentsCount: 8, landmark: 'Near Police Station' },
      { id: 'SP-102', stopName: 'Hebbal Flyover Junction', sequenceNo: 2, morningPickupTime: '07:15 AM', eveningDropTime: '03:55 PM', studentsCount: 12, landmark: 'Opposite Esteem Mall' },
      { id: 'SP-103', stopName: 'RT Nagar BDA Complex', sequenceNo: 3, morningPickupTime: '07:25 AM', eveningDropTime: '03:45 PM', studentsCount: 10, landmark: 'BDA Complex Entrance' },
      { id: 'SP-104', stopName: 'School Campus Gate A', sequenceNo: 4, morningPickupTime: '07:45 AM', eveningDropTime: '03:30 PM', studentsCount: 38, landmark: 'Main School Gate' },
    ],
  },
  {
    id: 'RT-02',
    routeName: 'South City Commute',
    routeCode: 'SCC-02',
    busNumber: 'BUS-02',
    driverName: 'Suresh Patil',
    attendantName: 'Lakshmi Nair',
    totalStops: 8,
    totalDistanceKm: 22.0,
    estimatedDurationMins: 55,
    totalStudentsAssigned: 42,
    status: 'Delayed',
    stops: [
      { id: 'SP-201', stopName: 'JP Nagar 6th Phase', sequenceNo: 1, morningPickupTime: '06:55 AM', eveningDropTime: '04:20 PM', studentsCount: 14, landmark: 'Near Central Park' },
      { id: 'SP-202', stopName: 'Jayanagar Metro Station', sequenceNo: 2, morningPickupTime: '07:10 AM', eveningDropTime: '04:05 PM', studentsCount: 15, landmark: 'Exit Gate B' },
      { id: 'SP-203', stopName: 'Lalbagh West Gate', sequenceNo: 3, morningPickupTime: '07:25 AM', eveningDropTime: '03:50 PM', studentsCount: 13, landmark: 'Ticket Counter' },
      { id: 'SP-204', stopName: 'School Campus Gate B', sequenceNo: 4, morningPickupTime: '07:50 AM', eveningDropTime: '03:30 PM', studentsCount: 42, landmark: 'Secondary School Gate' },
    ],
  },
  {
    id: 'RT-03',
    routeName: 'East Campus Line',
    routeCode: 'ECL-03',
    busNumber: 'BUS-03',
    driverName: 'Vikram Singh',
    attendantName: 'Anita Sharma',
    totalStops: 5,
    totalDistanceKm: 16.0,
    estimatedDurationMins: 40,
    totalStudentsAssigned: 32,
    status: 'Operational',
    stops: [
      { id: 'SP-301', stopName: 'Whitefield Value Mall', sequenceNo: 1, morningPickupTime: '07:05 AM', eveningDropTime: '04:15 PM', studentsCount: 10, landmark: 'Main Entrance' },
      { id: 'SP-302', stopName: 'Marathahalli Bridge', sequenceNo: 2, morningPickupTime: '07:20 AM', eveningDropTime: '04:00 PM', studentsCount: 12, landmark: 'Foot Over Bridge' },
      { id: 'SP-303', stopName: 'School Campus Gate A', sequenceNo: 3, morningPickupTime: '07:45 AM', eveningDropTime: '03:30 PM', studentsCount: 32, landmark: 'Main School Gate' },
    ],
  },
];

export const mockDrivers: DriverRecord[] = [
  {
    id: 'DRV-101',
    name: 'Rajesh Kumar',
    role: 'Driver',
    phone: '+91 98450 11223',
    licenseNumber: 'DL-04201800912',
    licenseExpiry: '2028-06-15',
    experienceYears: 12,
    medicalCertExpiry: '2027-01-10',
    assignedBusNumber: 'BUS-01',
    assignedRouteName: 'North Circuit Express',
    attendanceStatus: 'Present',
    performanceRating: 4.9,
  },
  {
    id: 'DRV-102',
    name: 'Suresh Patil',
    role: 'Driver',
    phone: '+91 98450 33445',
    licenseNumber: 'DL-04201500781',
    licenseExpiry: '2027-09-20',
    experienceYears: 9,
    medicalCertExpiry: '2026-11-05',
    assignedBusNumber: 'BUS-02',
    assignedRouteName: 'South City Commute',
    attendanceStatus: 'Present',
    performanceRating: 4.7,
  },
  {
    id: 'DRV-103',
    name: 'Vikram Singh',
    role: 'Driver',
    phone: '+91 98450 55667',
    licenseNumber: 'DL-04202000344',
    licenseExpiry: '2029-04-12',
    experienceYears: 7,
    medicalCertExpiry: '2027-05-18',
    assignedBusNumber: 'BUS-03',
    assignedRouteName: 'East Campus Line',
    attendanceStatus: 'Present',
    performanceRating: 4.8,
  },
  {
    id: 'ATT-201',
    name: 'Sunita Devi',
    role: 'Attendant',
    phone: '+91 98450 77889',
    licenseNumber: 'N/A',
    licenseExpiry: 'N/A',
    experienceYears: 5,
    medicalCertExpiry: '2027-02-15',
    assignedBusNumber: 'BUS-01',
    assignedRouteName: 'North Circuit Express',
    attendanceStatus: 'Present',
    performanceRating: 4.9,
  },
];

export const mockTrips: TripRecord[] = [
  {
    id: 'TRIP-901',
    tripName: 'Morning Pickup - Route 01',
    tripType: 'Morning Pickup',
    busNumber: 'BUS-01',
    driverName: 'Rajesh Kumar',
    routeName: 'North Circuit Express',
    scheduledStartTime: '07:00 AM',
    actualStartTime: '07:02 AM',
    scheduledEndTime: '07:45 AM',
    status: 'In Transit',
    delayMinutes: 0,
    studentsBoarded: 35,
    totalStudents: 38,
  },
  {
    id: 'TRIP-902',
    tripName: 'Morning Pickup - Route 02',
    tripType: 'Morning Pickup',
    busNumber: 'BUS-02',
    driverName: 'Suresh Patil',
    routeName: 'South City Commute',
    scheduledStartTime: '06:55 AM',
    actualStartTime: '07:10 AM',
    scheduledEndTime: '07:50 AM',
    status: 'Delayed',
    delayMinutes: 15,
    delayReason: 'Metro Construction Traffic Bottleneck at Jayanagar',
    studentsBoarded: 38,
    totalStudents: 42,
  },
  {
    id: 'TRIP-903',
    tripName: 'Morning Pickup - Route 03',
    tripType: 'Morning Pickup',
    busNumber: 'BUS-03',
    driverName: 'Vikram Singh',
    routeName: 'East Campus Line',
    scheduledStartTime: '07:05 AM',
    actualStartTime: '07:05 AM',
    scheduledEndTime: '07:45 AM',
    actualEndTime: '07:42 AM',
    status: 'Completed',
    delayMinutes: 0,
    studentsBoarded: 32,
    totalStudents: 32,
  },
];

export const mockGpsPoints: GpsTrackingPoint[] = [
  {
    busId: 'BUS-01',
    busNumber: 'BUS-01',
    routeName: 'North Circuit Express',
    driverName: 'Rajesh Kumar',
    currentLat: 13.0358,
    currentLng: 77.597,
    speedKmH: 38,
    heading: 'NE',
    currentStopName: 'Hebbal Flyover Junction',
    nextStopName: 'RT Nagar BDA Complex',
    etaMinsNextStop: 6,
    status: 'In Motion',
    lastPingTime: 'Just now',
  },
  {
    busId: 'BUS-02',
    busNumber: 'BUS-02',
    routeName: 'South City Commute',
    driverName: 'Suresh Patil',
    currentLat: 12.925,
    currentLng: 77.5938,
    speedKmH: 12,
    heading: 'N',
    currentStopName: 'Jayanagar Metro Station',
    nextStopName: 'Lalbagh West Gate',
    etaMinsNextStop: 18,
    status: 'Speed Warning',
    lastPingTime: '1 min ago',
  },
  {
    busId: 'BUS-03',
    busNumber: 'BUS-03',
    routeName: 'East Campus Line',
    driverName: 'Vikram Singh',
    currentLat: 12.9698,
    currentLng: 77.7499,
    speedKmH: 0,
    heading: 'E',
    currentStopName: 'School Campus Gate A',
    nextStopName: 'Trip Completed',
    etaMinsNextStop: 0,
    status: 'Stopped',
    lastPingTime: '2 mins ago',
  },
];

export const mockFuelLogs: FuelLogEntry[] = [
  {
    id: 'FL-501',
    busNumber: 'BUS-01',
    date: '2026-07-21',
    fuelLitres: 45,
    costPerLitre: 94.5,
    totalCost: 4252.5,
    odometerReadingKm: 42500,
    fillingStation: 'Indian Oil Depot - Yelahanka',
    mileageKmL: 4.8,
    filledBy: 'Rajesh Kumar',
  },
  {
    id: 'FL-502',
    busNumber: 'BUS-02',
    date: '2026-07-20',
    fuelLitres: 50,
    costPerLitre: 94.5,
    totalCost: 4725.0,
    odometerReadingKm: 38900,
    fillingStation: 'Bharat Petroleum - Jayanagar',
    mileageKmL: 4.2,
    filledBy: 'Suresh Patil',
  },
];

export const mockMaintenanceLogs: MaintenanceRecord[] = [
  {
    id: 'MNT-801',
    busNumber: 'BUS-04',
    serviceType: 'Oil & Filter',
    serviceDate: '2026-07-20',
    nextDueDate: '2026-10-20',
    cost: 8500,
    vendorName: 'Tata Motors Authorized Service Center',
    status: 'In Progress',
    notes: 'Scheduled 50,000 km general servicing & synthetic engine oil replacement.',
  },
  {
    id: 'MNT-802',
    busNumber: 'BUS-01',
    serviceType: 'Tyre Replacement',
    serviceDate: '2026-06-12',
    nextDueDate: '2026-12-12',
    cost: 32000,
    vendorName: 'Apollo Tyres Commercial Hub',
    status: 'Completed',
    notes: 'Replaced rear dual tires with heavy duty tread.',
  },
];

export const mockVehicleDocuments: VehicleDocument[] = [
  {
    id: 'DOC-101',
    busNumber: 'BUS-01',
    docType: 'Insurance Policy',
    documentNumber: 'INS-2026-99012',
    issueDate: '2025-11-16',
    expiryDate: '2026-11-15',
    issuingAuthority: 'ICICI Lombard General Insurance',
    status: 'Valid',
  },
  {
    id: 'DOC-102',
    busNumber: 'BUS-04',
    docType: 'Pollution (PUC)',
    documentNumber: 'PUC-KA01-8812',
    issueDate: '2026-02-02',
    expiryDate: '2026-08-01',
    issuingAuthority: 'RTO Bangalore Central',
    status: 'Expiring Soon',
  },
  {
    id: 'DOC-103',
    busNumber: 'BUS-02',
    docType: 'Fitness Certificate',
    documentNumber: 'FIT-2025-4412',
    issueDate: '2025-12-19',
    expiryDate: '2026-12-18',
    issuingAuthority: 'Karnataka RTO Transport Dept',
    status: 'Valid',
  },
];

export const mockTransportRequests: TransportRequestItem[] = [
  {
    id: 'REQ-301',
    studentId: 'STU-120',
    studentName: 'Ananya Sen',
    classGrade: 'Class 9-B',
    requestType: 'New Allocation',
    requestedRoute: 'North Circuit Express',
    requestedStop: 'Hebbal Flyover Junction',
    reason: 'Family relocated near Esteem Mall.',
    requestDate: '2026-07-22',
    status: 'Pending',
  },
  {
    id: 'REQ-302',
    studentId: 'STU-135',
    studentName: 'Kabir Nair',
    classGrade: 'Class 11-A',
    requestType: 'Stop Change',
    currentRoute: 'South City Commute',
    requestedRoute: 'South City Commute',
    requestedStop: 'Jayanagar Metro Station',
    reason: 'Convenient metro connectivity.',
    requestDate: '2026-07-21',
    status: 'Pending',
  },
];

export const mockSafetyIncidents: SafetyIncidentRecord[] = [
  {
    id: 'INC-701',
    busNumber: 'BUS-02',
    driverName: 'Suresh Patil',
    incidentType: 'Speed Violation',
    date: '2026-07-18',
    time: '07:35 AM',
    location: 'Outer Ring Road Flyover',
    severity: 'Medium',
    status: 'Resolved',
    actionTaken: 'GPS alert triggered at 52 km/h. Driver issued verbal warning and safety counseling.',
  },
];

export const mockAiTransportInsights: AiTransportInsight[] = [
  {
    id: 'INS-TR-01',
    type: 'delay_risk',
    title: 'Traffic Delay Risk Warning: Route 02',
    description: 'Metro construction at Jayanagar causes an average 15-minute delay during morning peak hours (7:10 AM - 7:30 AM).',
    metric: '15m Delay',
    actionText: 'Reroute via Bannerghatta Road',
    impact: 'High',
  },
  {
    id: 'INS-TR-02',
    type: 'fuel_eff',
    title: 'EV Fleet Conversion Savings',
    description: 'BUS-03 (EV) reduced monthly fuel cost by 62% compared to Diesel BUS-01 on similar route distances.',
    metric: '62% Savings',
    actionText: 'View EV ROI Analysis',
    impact: 'Medium',
  },
  {
    id: 'INS-TR-03',
    type: 'maintenance_pred',
    title: 'Predictive Brake Service Alert',
    description: 'BUS-02 telematics data indicates wear on brake pads after 38,900 km of heavy city stop-and-go driving.',
    metric: 'Brake Pad Wear',
    actionText: 'Schedule Service Desk PO',
    impact: 'High',
  },
];
