import type {
  AuditChecklistItem,
  DepartmentAuditItem,
  TeacherAuditCompliance,
  CurriculumComplianceItem,
  CorrectiveActionItem,
  AIAuditInsight,
  AuditAlert,
} from './types';

export const mockChecklistItems: AuditChecklistItem[] = [
  {
    id: 'chk-1',
    category: 'Curriculum Coverage',
    compliancePct: 91,
    status: 'Compliant',
    lastReviewedDate: 'Aug 04, 2026',
    riskLevel: 'Low',
    reviewer: 'Academic Board',
  },
  {
    id: 'chk-2',
    category: 'Lesson Plans',
    compliancePct: 96,
    status: 'Compliant',
    lastReviewedDate: 'Aug 05, 2026',
    riskLevel: 'Low',
    reviewer: 'HOD Committee',
  },
  {
    id: 'chk-3',
    category: 'Homework Compliance',
    compliancePct: 92,
    status: 'Compliant',
    lastReviewedDate: 'Aug 03, 2026',
    riskLevel: 'Low',
    reviewer: 'Quality Cell',
  },
  {
    id: 'chk-4',
    category: 'Assignments Ops',
    compliancePct: 94,
    status: 'Compliant',
    lastReviewedDate: 'Aug 04, 2026',
    riskLevel: 'Low',
    reviewer: 'Academic Coordinator',
  },
  {
    id: 'chk-5',
    category: 'Online Classes Telemetry',
    compliancePct: 95,
    status: 'Compliant',
    lastReviewedDate: 'Aug 05, 2026',
    riskLevel: 'Low',
    reviewer: 'EdTech Cell',
  },
  {
    id: 'chk-6',
    category: 'Online Exams & Proctoring',
    compliancePct: 89,
    status: 'Needs Review',
    lastReviewedDate: 'Aug 02, 2026',
    riskLevel: 'Moderate',
    reviewer: 'Exam Board',
  },
  {
    id: 'chk-7',
    category: 'Question Bank Taxonomy',
    compliancePct: 94,
    status: 'Compliant',
    lastReviewedDate: 'Aug 01, 2026',
    riskLevel: 'Low',
    reviewer: 'Subject Experts',
  },
  {
    id: 'chk-8',
    category: 'Student Assessments',
    compliancePct: 89,
    status: 'Needs Review',
    lastReviewedDate: 'Jul 30, 2026',
    riskLevel: 'Moderate',
    reviewer: 'Academic Board',
  },
  {
    id: 'chk-9',
    category: 'Attendance Compliance',
    compliancePct: 98,
    status: 'Compliant',
    lastReviewedDate: 'Aug 05, 2026',
    riskLevel: 'Low',
    reviewer: 'Attendance Cell',
  },
  {
    id: 'chk-10',
    category: 'Teacher Documentation',
    compliancePct: 93,
    status: 'Compliant',
    lastReviewedDate: 'Aug 03, 2026',
    riskLevel: 'Low',
    reviewer: 'HR & Quality',
  },
];

export const mockDepartmentAudits: DepartmentAuditItem[] = [
  {
    id: 'dept-1',
    departmentName: 'Mathematics',
    headName: 'Dr. Rajesh Sharma',
    headAvatar:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150',
    compliancePct: 98.4,
    auditScore: 98,
    pendingIssuesCount: 0,
    criticalFindingsCount: 0,
    auditDate: 'Aug 02, 2026',
    status: 'Healthy',
  },
  {
    id: 'dept-2',
    departmentName: 'Physics & Natural Sciences',
    headName: 'Mrs. Kavitha Menon',
    headAvatar:
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=150',
    compliancePct: 96.0,
    auditScore: 96,
    pendingIssuesCount: 1,
    criticalFindingsCount: 0,
    auditDate: 'Jul 28, 2026',
    status: 'Healthy',
  },
  {
    id: 'dept-3',
    departmentName: 'Chemistry',
    headName: 'Dr. Sonia Gandhi',
    headAvatar:
      'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=150',
    compliancePct: 84.5,
    auditScore: 85,
    pendingIssuesCount: 4,
    criticalFindingsCount: 1,
    auditDate: 'Aug 01, 2026',
    status: 'Advisory',
  },
  {
    id: 'dept-4',
    departmentName: 'Social Studies & Humanities',
    headName: 'Mrs. Anita Desai',
    headAvatar:
      'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=150',
    compliancePct: 78.2,
    auditScore: 78,
    pendingIssuesCount: 6,
    criticalFindingsCount: 2,
    auditDate: 'Jul 25, 2026',
    status: 'At Risk',
  },
  {
    id: 'dept-5',
    departmentName: 'Computer Science',
    headName: 'Prof. Vikramaditya Verma',
    headAvatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150',
    compliancePct: 95.2,
    auditScore: 95,
    pendingIssuesCount: 1,
    criticalFindingsCount: 0,
    auditDate: 'Aug 03, 2026',
    status: 'Healthy',
  },
];

export const mockTeacherAuditList: TeacherAuditCompliance[] = [
  {
    id: 'tac-1',
    teacherName: 'Dr. Rajesh Sharma',
    avatar:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150',
    department: 'Mathematics',
    lessonPlansPct: 100,
    homeworkPct: 98,
    assignmentsPct: 98,
    attendancePct: 99,
    assessmentPct: 98,
    syllabusPct: 98,
    overallScorePct: 98.5,
    riskLevel: 'Low',
  },
  {
    id: 'tac-2',
    teacherName: 'Mrs. Kavitha Menon',
    avatar:
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=150',
    department: 'Physics',
    lessonPlansPct: 96,
    homeworkPct: 94,
    assignmentsPct: 96,
    attendancePct: 98,
    assessmentPct: 95,
    syllabusPct: 96,
    overallScorePct: 95.8,
    riskLevel: 'Low',
  },
  {
    id: 'tac-3',
    teacherName: 'Dr. Sonia Gandhi',
    avatar:
      'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=150',
    department: 'Chemistry',
    lessonPlansPct: 84,
    homeworkPct: 82,
    assignmentsPct: 85,
    attendancePct: 94,
    assessmentPct: 80,
    syllabusPct: 82,
    overallScorePct: 84.5,
    riskLevel: 'Moderate',
  },
  {
    id: 'tac-4',
    teacherName: 'Mrs. Anita Desai',
    avatar:
      'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=150',
    department: 'Social Studies',
    lessonPlansPct: 76,
    homeworkPct: 75,
    assignmentsPct: 78,
    attendancePct: 92,
    assessmentPct: 74,
    syllabusPct: 76,
    overallScorePct: 78.5,
    riskLevel: 'High',
  },
];

export const mockCurriculumComplianceList: CurriculumComplianceItem[] = [
  {
    id: 'curr-1',
    subject: 'Higher Mathematics',
    grade: 'Grade 10 A',
    teacherName: 'Dr. Rajesh Sharma',
    expectedProgressPct: 95,
    actualProgressPct: 98,
    variancePct: +3,
    status: 'On Track',
    riskLevel: 'Low',
  },
  {
    id: 'curr-2',
    subject: 'Electromagnetism',
    grade: 'Grade 11 B',
    teacherName: 'Mrs. Kavitha Menon',
    expectedProgressPct: 95,
    actualProgressPct: 96,
    variancePct: +1,
    status: 'On Track',
    riskLevel: 'Low',
  },
  {
    id: 'curr-3',
    subject: 'Organic Chemistry',
    grade: 'Grade 12 A',
    teacherName: 'Dr. Sonia Gandhi',
    expectedProgressPct: 95,
    actualProgressPct: 82,
    variancePct: -13,
    status: 'Slight Lag',
    riskLevel: 'Moderate',
  },
  {
    id: 'curr-4',
    subject: 'French Revolution History',
    grade: 'Grade 9 B',
    teacherName: 'Mrs. Anita Desai',
    expectedProgressPct: 95,
    actualProgressPct: 76,
    variancePct: -19,
    status: 'Critical Delay',
    riskLevel: 'High',
  },
];

export const mockCorrectiveActions: CorrectiveActionItem[] = [
  {
    id: 'ca-101',
    issueTitle: 'Grade 9 History syllabus delay (-19% vs target)',
    department: 'Social Studies',
    assignedTo: 'Mrs. Anita Desai',
    priority: 'High',
    deadline: 'Aug 14, 2026',
    progressPct: 40,
    status: 'In Progress',
    commentsCount: 3,
  },
  {
    id: 'ca-102',
    issueTitle: 'Organic Chemistry evaluation turnaround > 48 hrs SLA',
    department: 'Chemistry',
    assignedTo: 'Dr. Sonia Gandhi',
    priority: 'High',
    deadline: 'Aug 10, 2026',
    progressPct: 60,
    status: 'In Progress',
    commentsCount: 2,
  },
  {
    id: 'ca-103',
    issueTitle: 'Grade 11 Physics lab notebook compliance audit',
    department: 'Physics',
    assignedTo: 'Mrs. Kavitha Menon',
    priority: 'Medium',
    deadline: 'Aug 18, 2026',
    progressPct: 90,
    status: 'Under Verification',
    commentsCount: 4,
  },
];

export const mockAIAuditInsights: AIAuditInsight[] = [
  {
    id: 'ai-aud-1',
    type: 'Department Risk',
    severity: 'Critical',
    title: 'Social Studies Department Requires Quality Intervention',
    description: 'Syllabus progress is 19% behind schedule across Grade 9 sections.',
    affectedTarget: 'Social Studies Department',
    suggestedIntervention: 'Schedule extra tutorial hours & assign HOD co-teaching.',
  },
  {
    id: 'ai-aud-2',
    type: 'Assessment Quality',
    severity: 'Warning',
    title: 'Chemistry Question Paper Difficulty Imbalance',
    description:
      'Mid-Term draft paper contains only 10% HOTS questions vs required 20% CBSE blueprint.',
    affectedTarget: 'Grade 12 Chemistry Exam Paper',
    suggestedIntervention: 'Request Q-Paper author to replace 3 MCQs with HOTS numerical items.',
  },
  {
    id: 'ai-aud-3',
    type: 'Curriculum Delay',
    severity: 'Info',
    title: 'Predicted Mid-Term Completion Rate: 94.8%',
    description:
      '5 out of 6 departments are on track to achieve 100% syllabus completion before August 25.',
    affectedTarget: 'Institutional Mid-Term Readiness',
    suggestedIntervention: 'Conduct final HOD review on August 12.',
  },
];

export const mockAuditAlerts: AuditAlert[] = [
  {
    id: 'alt-aud-1',
    timestamp: '10:00 AM',
    type: 'Syllabus Delay',
    severity: 'high',
    title: 'Grade 9 Social Studies 19% behind mid-term schedule',
    details: 'Corrective action plan required by Friday.',
    resolved: false,
  },
  {
    id: 'alt-aud-2',
    timestamp: '09:15 AM',
    type: 'Lesson Plan Missed',
    severity: 'medium',
    title: '3 lesson plans pending HOD signoff',
    details: 'Chemistry department weekly lesson plan submission overdue.',
    resolved: false,
  },
  {
    id: 'alt-aud-3',
    timestamp: '08:30 AM',
    type: 'Homework Compliance Drop',
    severity: 'low',
    title: 'Grade 8 English homework compliance dropped 4%',
    details: 'Weekly review completed by Quality Cell.',
    resolved: true,
  },
];
